/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2024-10-15 11:44:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1728799185724L));
    _jspx_dependants.put("jar:file:/D:/2%20nd%20year/1%20st%20semester/MY/Assignment/OOP/sep%20servlet%20-%20Copyvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TrainGO/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664433678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");

	if(session.getAttribute("gardUsername")==null){
		response.sendRedirect("Login.jsp");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <!-- Link to Font Awesome icons -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("        <!-- Link to custom style sheet for additional styling -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"CSS/style.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <!-- Header section -->\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <div><h1>TrainGo</h1></div>\r\n");
      out.write("        \r\n");
      out.write("        <div>    \r\n");
      out.write("            <div class=\"mysts\">\r\n");
      out.write("                <!-- Button to reload the train schedule -->\r\n");
      out.write("                <a href=\"Read_Schedule_SV\"><button class=\"header_but\">Reload Schedule</button></a>\r\n");
      out.write("            \r\n");
      out.write("                <!-- Button to log out -->\r\n");
      out.write("                <a href=\"Logout_SV\"><button class=\"header_but\">Logout</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("  		</div> \r\n");
      out.write("  		</div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Image gallery section -->\r\n");
      out.write("        <div class=\"image_gallery\">\r\n");
      out.write("        \r\n");
      out.write("        <div><!-- logo, navigation bar-->\r\n");
      out.write("            <div><!--logo, navigation bar-->\r\n");
      out.write("                <div><!--logo-->\r\n");
      out.write("                    <!-- Logo can be inserted here -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <div><!--navigation bar-->\r\n");
      out.write("                    <div class=\"slider-images\">\r\n");
      out.write("                        <!-- Slider for image and details -->\r\n");
      out.write("                        <div class=\"slider-img\">\r\n");
      out.write("                            <img src=\"photo/1.jpeg\" alt=\"1\">\r\n");
      out.write("                            <h1>Update</h1>\r\n");
      out.write("                                <div class=\"details\">\r\n");
      out.write("                                    <h2>Update Journey Details</h2>\r\n");
      out.write("                                    <p>access the update interface to verify, mark completed, or Update Train Journey for accurate tracking</p>\r\n");
      out.write("                                    <button id=\"new_but1\" class=\"new_bt\">click for more</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"slider-img\">\r\n");
      out.write("                            <img src=\"photo/back6 (1).jpeg\" alt=\"2\">\r\n");
      out.write("                            <h1>Schedule</h1>\r\n");
      out.write("                                <div class=\"details\">\r\n");
      out.write("                                    <h2>Schedules Details</h2>\r\n");
      out.write("                                    <p>Access the schedule to explore train journeys, check timings, and view seat availability for a hassle-free travel experience.</p>\r\n");
      out.write("                                    <button id=\"new_but2\" class=\"new_bt\">View Schedule</button>\r\n");
      out.write("                                    \r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"slider-img\">\r\n");
      out.write("                            <img src=\"photo/3.jpeg\" alt=\"3\">\r\n");
      out.write("                            <h1>cancel</h1>\r\n");
      out.write("                                <div class=\"details\">\r\n");
      out.write("                                    <h2>Cancel Schedule</h2>\r\n");
      out.write("                                    <p>access the Cancellation interface to verify, mark completed, or cancel passenger bookings for accurate tracking</p>\r\n");
      out.write("                                    <button id=\"new_but3\" class=\"new_bt\">click for more</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"slider-img active\">\r\n");
      out.write("                            <img src=\"photo/4.jpeg\" alt=\"4\">\r\n");
      out.write("                            <h1>Create</h1>\r\n");
      out.write("                                <div class=\"details\">\r\n");
      out.write("                                    <h2>Add New Train schedule</h2>\r\n");
      out.write("                                    <p>access the Train schedule interface to view and Add New Train schedule. Mark completed reservations for accurate tracking.</p>\r\n");
      out.write("                                    <button id=\"new_but4\" class=\"new_bt\">click for more</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"slider-img\">\r\n");
      out.write("                            <img src=\"photo/5.jpeg\" alt=\"5\">\r\n");
      out.write("                            <h1>Our Route</h1>\r\n");
      out.write("                                <div class=\"details\">\r\n");
      out.write("                                    <h2>Our Route</h2>\r\n");
      out.write("                                    <p>Our trains connect major cities and scenic destinations, ensuring quick, efficient travel on well-connected, expansive routes.</p>\r\n");
      out.write("                                    <button id=\"new_but5\" class=\"new_bt\">click for more</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"slider-img\">\r\n");
      out.write("                            <img src=\"photo/6.jpeg\" alt=\"6\">\r\n");
      out.write("                            <h1>Safety</h1>\r\n");
      out.write("                                <div class=\"details\">\r\n");
      out.write("                                    <h2>Our Commitment to Safety</h2>\r\n");
      out.write("                                    <p>Your safety matters. We prioritize hygiene, advanced safety technology, and trained staff to ensure a secure travel experience.</p>\r\n");
      out.write("                                    <button id=\"new_but6\" class=\"new_bt\">click for more</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"slider-img\">\r\n");
      out.write("                            <img src=\"photo/7.jpeg\" alt=\"7\">\r\n");
      out.write("                            <h1>History</h1>\r\n");
      out.write("                                <div class=\"details\">\r\n");
      out.write("                                    <h2>Our History</h2>\r\n");
      out.write("                                    <p>With over 20 years of service, we've grown into a trusted network, connecting cities and ensuring reliable travel.</p>\r\n");
      out.write("                                    <button id=\"new_but7\" class=\"new_bt\">click for more</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Script for handling slider functionality -->\r\n");
      out.write("        <script>\r\n");
      out.write("            document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("                const sliderImages = document.querySelectorAll('.slider-img');\r\n");
      out.write("        \r\n");
      out.write("                // Add click event to each slider image\r\n");
      out.write("                sliderImages.forEach(function(image) {\r\n");
      out.write("                    image.addEventListener('click', function() {\r\n");
      out.write("                        // Remove active class from all images\r\n");
      out.write("                        sliderImages.forEach(function(img) {\r\n");
      out.write("                            img.classList.remove('active');\r\n");
      out.write("                        });\r\n");
      out.write("                        // Add active class to the clicked image\r\n");
      out.write("                        this.classList.add('active');\r\n");
      out.write("                    });\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"about_para\">\r\n");
      out.write("        \r\n");
      out.write("    <hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Section for adding a new train journey -->\r\n");
      out.write("    <div class=\"addtrn\" id=\"addtrn\"><!--Add New Train journey-->\r\n");
      out.write("        <h1>Add New Train journey</h1><br>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"Cancellation-form\">\r\n");
      out.write("                <form action=\"GCreate\" method=\"post\">\r\n");
      out.write("                    <!-- Input field for journey name -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Train_ID\">Enter journey Name :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"journey_name\" id=\"Add_Train_Name\" placeholder=\"\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for train ID -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter Train ID :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"train_id\" id=\"Add_train_id\" placeholder=\"Trn _ _ _ _ _ _\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for train name -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter Train Name :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"train_name\" id=\"Add_train_id\" placeholder=\"Trn _ _ _ _ _ _\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for train start time -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter Train Start Time :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"start\" id=\"Add_start_time\" placeholder=\"AM / PM\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for train start location -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter Train Start Location :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"start_loc\" id=\"Add_start_loc\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for train end location -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter Train End Location :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"end_loc\" id=\"Add_end_loc\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for train arrival time -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Train_ID\">Enter Train Arrival Time :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"arrival\" id=\"Add_Arrival_time\" placeholder=\"AM / PM\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for train capacity -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter Train Capacity :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"capacity\" id=\"Add_cap\" placeholder=\"FULL Seat Count\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for third-class seat count -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Train_ID\">Enter 3rd Class Seat Count :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"three\" id=\"Add_3rd\" placeholder=\"\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for first-class seat count -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter 1st Class Seat Count :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"one\" id=\"Add_1st\" placeholder=\"\" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Button to submit the form to add the journey -->\r\n");
      out.write("                    <a href=\"Read_Schedule_SV\"><button type=\"submit\">Add Journey</button></a>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("                <!-- Image related to the form -->\r\n");
      out.write("                <div class=\"image-container\">\r\n");
      out.write("                    <img src=\"photo/back8.jpeg\" alt=\"Mug Image\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <h2>Train scheduling Form</h2>\r\n");
      out.write("            </div>        \r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Section for displaying the table of train information -->\r\n");
      out.write("    <div class=\"table-container\" id=\"table-container\"><!--Checker Interface-->\r\n");
      out.write("        <h1>Train Information</h1><br>\r\n");
      out.write("\r\n");
      out.write("        <table>\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>                        \r\n");
      out.write("                    <th>Journey ID</th>\r\n");
      out.write("                    <th>Journey Name</th>\r\n");
      out.write("                    <th>Train ID</th>\r\n");
      out.write("                    <th>Train Name</th>\r\n");
      out.write("                    <th>Start Time</th>\r\n");
      out.write("                    <th>Start Location</th>\r\n");
      out.write("                    <th>End Location</th>\r\n");
      out.write("                    <th>Arrival Time</th>\r\n");
      out.write("                    <th>Capacity</th>\r\n");
      out.write("                    <th>Third Class Seat Count</th>\r\n");
      out.write("                    <th>First Class Seat Count</th>\r\n");
      out.write("                    <th>Option</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                <!-- Iterates over the journeys to populate the table -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Section for canceling a train journey -->\r\n");
      out.write("    <div class=\"Cancellation\" id=\"Cancellation\"><!--cancel train journey-->\r\n");
      out.write("        <h1>Cancel Train Journey</h1><br>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"Cancellation-form\">\r\n");
      out.write("            \r\n");
      out.write("                <form action=\"GDelete\" method=\"post\">\r\n");
      out.write("                    ");
  String Djourney_id = request.getParameter("delete_jid");
                        String Dtrain_id = request.getParameter("delete_tid");
                    
      out.write("\r\n");
      out.write("                    <!-- Input field for journey ID (readonly) -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Train_ID\">Enter journey ID :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"Djourney_id\" id=\"Train_ID\" value=");
      out.print(Djourney_id);
      out.write(" readonly>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for train ID (readonly) -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter Train ID :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"Dtrain_id\" id=\"Reservation_id\" value=");
      out.print(Dtrain_id);
      out.write(" readonly>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Text area for special notes -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"username\">Any Special Notes :</label>\r\n");
      out.write("                        <textarea name=\"DSsp_note\" id=\"username\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Button to submit the cancellation -->\r\n");
      out.write("                    <button type=\"submit\">Cancel Reservation</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Image related to the form -->\r\n");
      out.write("                <div class=\"image-container\">\r\n");
      out.write("                    <img src=\"photo/back5.jpeg\" alt=\"Mug Image\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <h2>Train Cancellation Form</h2>\r\n");
      out.write("            </div>        \r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Section for updating a train journey -->\r\n");
      out.write("    <div class=\"update\" id=\"updatetrain\"><!--UPDARE Train journey-->\r\n");
      out.write("        <h1>Update Train journey</h1><br>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"Cancellation-form\">\r\n");
      out.write("                \r\n");
      out.write("                <form action=\"GUpdate\" method=\"post\">\r\n");
      out.write("                    ");
  String Ujourney_id = request.getParameter("jid");
                        String Ujourney_name = request.getParameter("jname");
                        String Utrain_id = request.getParameter("tid");
                        String Utrain_name = request.getParameter("tname");
                        String Ustart = request.getParameter("stime");
                        String Usloc = request.getParameter("sloc");        
                        String Ueloc = request.getParameter("eloc");        
                        String Uarrival = request.getParameter("atime");
                        String Ucapacity = request.getParameter("cap");
                        String Uthree = request.getParameter("third");
                        String Uone = request.getParameter("one");
                    
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- Input field for journey ID (readonly) -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Train_ID\">journey ID :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"Ujourney_id\" id=\"Add_Train_ID\" value=");
      out.print(Ujourney_id);
      out.write(" readonly>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for new journey name -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Train_ID\">Enter New journey Name :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"Ujourney_name\" id=\"Add_Train_Name\" value=");
      out.print(Ujourney_name);
      out.write(" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for new train ID -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter New Train ID :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"Utrain_id\" id=\"Add_train_id\" value=");
      out.print(Utrain_id);
      out.write(" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for new train name -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter New Train Name :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"Utrain_name\" id=\"Add_train_name\" value=");
      out.print(Utrain_name);
      out.write(" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for new train start time -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter New Train Start Time :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"Ustart\" id=\"Add_start_time\" value=");
      out.print(Ustart);
      out.write(" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for new train start location -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter New Train Start Location :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"Ustart_loc\" id=\"Add_start_loc\" value=");
      out.print(Usloc);
      out.write(" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for new train end location -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter New Train End Location :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"Uend_loc\" id=\"Add_end_loc\" value=");
      out.print(Ueloc);
      out.write(" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for new train arrival time -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Train_ID\">Enter New Train Arrival Time :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"Uarrival\" id=\"Add_Arrival_time\" value=");
      out.print(Uarrival);
      out.write(" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for new train capacity -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter New Train Capacity :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"Ucapacity\" id=\"Add_cap\" value=");
      out.print(Ucapacity);
      out.write(" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for new third-class seat count -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Train_ID\">Enter New 3rd Class Seat Count :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"Uthree\" id=\"Add_3rd\" value=");
      out.print(Uthree);
      out.write(" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Input field for new first-class seat count -->\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <label for=\"Reservation_id\">Enter New 1st Class Seat Count :</label>\r\n");
      out.write("                        <input type=\"text\" name=\"Uone\" id=\"Add_1st\" value=");
      out.print(Uone);
      out.write(" required>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Button to submit the update -->\r\n");
      out.write("                    <a href=\"Read_Schedule_SV\"><button type=\"submit\">Update Journey</button></a>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("                <!-- Image related to the form -->\r\n");
      out.write("                <div class=\"image-container\">\r\n");
      out.write("                    <img src=\"photo/back6 (2).jpeg\" alt=\"Mug Image\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <h2>Train Update Form</h2>\r\n");
      out.write("\r\n");
      out.write("            </div>        \r\n");
      out.write("                \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("<!-- Section for displaying the services offered -->\r\n");
      out.write("<div class=\"services\" id=\"services\"><!--our services-->\r\n");
      out.write("    <h1>Our Services</h1><br>\r\n");
      out.write("    <p>We are dedicated to offering services that simplify your travel experience from start to finish. Our online booking system is easy to use, allowing you to reserve your tickets in just a few clicks. In addition to booking, we offer real-time updates on train schedules and delays so you can plan your trip with confidence. Once onboard, stay connected with free Wi-Fi available in all coaches, and keep your devices powered up with convenient charging points at every seat. We also provide a selection of snacks and meals for you to enjoy during your trip. If you ever have a question or concern, our 24/7 customer service team is always available to assist. We aim to make every aspect of your journey as smooth and hassle-free as possible, whether you’re a daily commuter or traveling long-distance. Your comfort, convenience, and satisfaction are our top priorities as we strive to enhance your travel experience.</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("<!-- Section for displaying the company's history -->\r\n");
      out.write("<div class=\"History\" id=\"History\"><!--Our History-->\r\n");
      out.write("    <h1>Our History</h1><br>\r\n");
      out.write("    <p>Our journey began over two decades ago with the simple goal of connecting communities through reliable train services. What started as a small operation has grown into one of the country’s most trusted rail networks. Over the years, we have expanded our routes, introduced new services, and continually improved to meet the evolving needs of our passengers. From our humble beginnings to our present-day network, we have always focused on providing safe, comfortable, and efficient travel for our customers. Our history is marked by innovation, such as the introduction of digital ticketing, real-time updates, and premium onboard services. We take great pride in the relationships we’ve built with the cities and communities we serve. Our commitment to excellence has helped us earn the loyalty of millions of passengers over the years. As we continue to grow, we remain dedicated to offering the best possible travel experience for all of our passengers.</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("<!-- Section for describing the train routes -->\r\n");
      out.write("<div class=\"Route\" id=\"Route\"><!--Our Route-->\r\n");
      out.write("    <h1>Our Route</h1><br>\r\n");
      out.write("    <p>Our extensive rail network connects cities and communities across the country, offering a convenient and efficient way to travel. Whether you’re commuting to work, visiting family, or embarking on a scenic journey, our routes are designed to get you where you need to go with ease. We operate on well-planned routes that minimize travel time while maximizing convenience, ensuring that you reach your destination quickly and comfortably. Our network spans both urban and rural areas, so whether you’re in a major city or a remote town, we have a route for you. Many of our routes feature breathtaking views of the countryside, coastlines, and mountains, making your journey not just about the destination but also the experience along the way. With frequent departures and arrivals, we offer flexibility to accommodate your schedule. Our goal is to provide you with a stress-free travel option that connects you to the places and people that matter most.</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("<!-- Section outlining the company's commitment to safety -->\r\n");
      out.write("<div class=\"Safety\" id=\"Safety\"><!--Our Commitment to Safety-->\r\n");
      out.write("    <h1>Our Commitment to Safety</h1><br>\r\n");
      out.write("    <p>Your safety is our highest priority, and we go above and beyond to ensure that every journey you take with us is secure. We have implemented state-of-the-art safety technologies on all of our trains, including advanced braking systems, surveillance cameras, and automated alerts to prevent potential hazards. Our trains undergo rigorous, regular inspections to ensure they meet the highest safety standards. In addition, all our staff are trained in emergency protocols and are equipped to handle any situation that may arise, giving you peace of mind throughout your journey. We also understand the importance of maintaining a clean environment onboard. Our cleaning crews thoroughly sanitize trains between journeys, and additional hygiene measures are in place to ensure a healthy travel experience. Whether it's safety from operational risks or health concerns, we take every precaution to protect our passengers, so you can enjoy a safe and worry-free trip every time.</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Script for smooth scrolling to different sections of the page -->\r\n");
      out.write("<script>\r\n");
      out.write("    document.getElementById('new_but1').addEventListener('click', function() {\r\n");
      out.write("        document.getElementById('updatetrain').scrollIntoView({ behavior: 'smooth' });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('new_but2').addEventListener('click', function() {\r\n");
      out.write("        document.getElementById('table-container').scrollIntoView({ behavior: 'smooth' });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('new_but3').addEventListener('click', function() {\r\n");
      out.write("        document.getElementById('Cancellation').scrollIntoView({ behavior: 'smooth' });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('new_but4').addEventListener('click', function() {\r\n");
      out.write("        document.getElementById('addtrn').scrollIntoView({ behavior: 'smooth' });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('new_but5').addEventListener('click', function() {\r\n");
      out.write("        document.getElementById('Route').scrollIntoView({ behavior: 'smooth' });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('new_but6').addEventListener('click', function() {\r\n");
      out.write("        document.getElementById('Safety').scrollIntoView({ behavior: 'smooth' });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('new_but7').addEventListener('click', function() {\r\n");
      out.write("        document.getElementById('History').scrollIntoView({ behavior: 'smooth' });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer section with quick access links and social media -->\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"footer-container\">\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Quick Access</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("                <li><a href=\"#\">Our Services</a></li>\r\n");
      out.write("                <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                <li><a href=\"#\">Cancellation Program</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Get Help</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("                <li><a href=\"#\">History</a></li>\r\n");
      out.write("                <li><a href=\"#\">Route</a></li>\r\n");
      out.write("                <li><a href=\"#\">Special</a></li>\r\n");
      out.write("                <li><a href=\"#\">Reservation</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Train Reservation</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">VIP Reservation</a></li>\r\n");
      out.write("                <li><a href=\"#\">Early Booking</a></li>\r\n");
      out.write("                <li><a href=\"#\">Special Day</a></li>\r\n");
      out.write("                <li><a href=\"#\">Food Order</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Follow Us</h3>\r\n");
      out.write("            <div class=\"footer-social\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-linkedin\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /Home.jsp(249,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("journey");
      // /Home.jsp(249,16) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/Home.jsp(249,16) '${journeys}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${journeys}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                    <tr>\r\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.journeyId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.journeyName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.trainId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.trainName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.trainStartTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.start_location}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.end_location}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>                   \r\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.trainArrivalTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.trainCapacity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.thirdSeat}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                        <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.firstSeat}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                        <!-- Links for updating and deleting a journey -->\r\n");
            out.write("                        <td>\r\n");
            out.write("                            <a class=\"update\" href=\"Home.jsp?jid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.journeyId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&jname=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.journeyName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&tid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.trainId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&tname=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.trainName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&stime=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.trainStartTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&sloc=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.start_location}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&eloc=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.end_location}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&atime=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.trainArrivalTime}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&cap=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.trainCapacity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&third=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.thirdSeat}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&one=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.firstSeat}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("#updatetrain\" id=\"update\">Update</a>\r\n");
            out.write("                            <a class=\"delete\" href=\"Home.jsp?delete_jid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.journeyId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&delete_tid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${journey.trainId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("#Cancellation\" id=\"delete\">Delete</a>\r\n");
            out.write("                        </td>\r\n");
            out.write("                    </tr>\r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
