/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2024-10-14 10:05:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>Home page</title>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"CSS/Homepage.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <div><h1>TrainGO</h1></div>\r\n");
      out.write("            <div class=\"mysts\">\r\n");
      out.write("                <a href=\"Login.jsp\"><button class=\"header_but\">Login</button></a>\r\n");
      out.write("                <a href=\"PassengerRegister.jsp\"><button class=\"header_but\">SignUp</button></a>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"image_gallery\">\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div><!-- logo, navigation bar-->\r\n");
      out.write("            <div><!--logo, navigation bar-->\r\n");
      out.write("                <div><!--logo-->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div><!--navigation bar-->\r\n");
      out.write("                    <div class=\"slider-images\">\r\n");
      out.write("                        <div class=\"slider-img\">\r\n");
      out.write("                            <img src=\"photo/1.jpeg\" alt=\"1\">\r\n");
      out.write("                            <h1>Services</h1>\r\n");
      out.write("                                <div class=\"details\">\r\n");
      out.write("                                    <h2>Our Services</h2>\r\n");
      out.write("                                    <p>Offering easy booking, 24/7 customer support, onboard Wi-Fi, charging points, and real-time updates for a seamless travel experience.</p>\r\n");
      out.write("                                    <button id=\"new_but2\" class=\"new_bt\">click for more</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"slider-img\">\r\n");
      out.write("                            <img src=\"photo/back6 (1).jpeg\" alt=\"2\">\r\n");
      out.write("                            <h1>cancel</h1>\r\n");
      out.write("                            <div class=\"details\">\r\n");
      out.write("                                <h2>cancel reservation</h2>\r\n");
      out.write("                                <p>access the Cancellation interface to verify, mark completed, or cancel passenger bookings for accurate tracking</p>\r\n");
      out.write("                                <a href=\"searchTicket.jsp\" style=\"text-decoration: none;\"><button class=\"new_bt\">click for more</button></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"slider-img\">\r\n");
      out.write("                            <img src=\"photo/3.jpeg\" alt=\"3\">\r\n");
      out.write("                            <h1>Reservation</h1>\r\n");
      out.write("                                <div class=\"details\">\r\n");
      out.write("                                    <h2>make reservation</h2>\r\n");
      out.write("                                    <p>Easily book your train tickets with TrainGO, selecting routes, seats, and times, all in just a few quick steps.</p>\r\n");
      out.write("                                     <a href=\"reservation.jsp\" style=\"text-decoration: none;\"><button  class=\"new_bt\">click for more</button></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"slider-img active\">\r\n");
      out.write("                            <img src=\"photo/4.jpeg\" alt=\"4\">\r\n");
      out.write("                            <h1>Home</h1>\r\n");
      out.write("                                <div class=\"details\">\r\n");
      out.write("                                    <h2>Welcome to TrainGO</h2>\r\n");
      out.write("                                    <p>TrainGO is an advanced online train reservation system designed to simplify the process of booking train tickets. \r\n");
      out.write("                                        It provides users with a seamless experience to search for available trains, view schedules, book tickets, and manage \r\n");
      out.write("                                        reservations all from a single platform. With user-friendly navigation and secure payment integration, TrainGO ensures\r\n");
      out.write("                                         a hassle-free journey planning experience, making train travel more convenient and accessible for everyone.</p>\r\n");
      out.write("                                   \r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"slider-img\">\r\n");
      out.write("                            <img src=\"photo/5.jpeg\" alt=\"5\">\r\n");
      out.write("                            <h1>Our Route</h1>\r\n");
      out.write("                                <div class=\"details\">\r\n");
      out.write("                                    <h2>Our Route</h2>\r\n");
      out.write("                                    <p>Our trains connect major cities and scenic destinations, ensuring quick, efficient travel on well-connected, expansive routes.</p>\r\n");
      out.write("                                    <button id=\"new_but5\" class=\"new_bt\">click for more</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"slider-img\">\r\n");
      out.write("                            <img src=\"photo/6.jpeg\" alt=\"6\">\r\n");
      out.write("                            <h1>Review</h1>\r\n");
      out.write("                                <div class=\"details\">\r\n");
      out.write("                                    <h2>Our Review</h2>\r\n");
      out.write("                                    <p>Share your feedback, rate your travel experience, and read reviews from other passengers. You can edit or delete your reviews and browse through ratings sorted by date, rating, or helpfulness. Your input helps us improve our services!</p>\r\n");
      out.write("                                    <a href=\"addreview.jsp\" style=\"text-decoration: none;\"><button  class=\"new_bt\">click for more</button></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"slider-img\">\r\n");
      out.write("                            <img src=\"photo/7.jpeg\" alt=\"7\">\r\n");
      out.write("                            <h1>History</h1>\r\n");
      out.write("                                <div class=\"details\">\r\n");
      out.write("                                    <h2>Our History</h2>\r\n");
      out.write("                                    <p>With over 20 years of service, we've grown into a trusted network, connecting cities and ensuring reliable travel.</p>\r\n");
      out.write("                                    <button id=\"new_but7\" class=\"new_bt\">click for more</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("                const sliderImages = document.querySelectorAll('.slider-img');\r\n");
      out.write("        \r\n");
      out.write("                sliderImages.forEach(function(image) {\r\n");
      out.write("                    image.addEventListener('mouseenter', function() {\r\n");
      out.write("                        sliderImages.forEach(function(img) {\r\n");
      out.write("                            img.classList.remove('active');\r\n");
      out.write("                        });\r\n");
      out.write("                        this.classList.add('active'); // Set the hovered image as active\r\n");
      out.write("                    });\r\n");
      out.write("        \r\n");
      out.write("                    image.addEventListener('mouseleave', function() {\r\n");
      out.write("                        this.classList.remove('active'); // Remove active class on mouse leave\r\n");
      out.write("                    });\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        <hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"about_para\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"table-container\" id=\"table-container\"><!--Checker Interface-->\r\n");
      out.write("            <h1>Train Information</h1><br>\r\n");
      out.write("\r\n");
      out.write("                <table>\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>Train ID</th>\r\n");
      out.write("                            <th>Train Name</th>\r\n");
      out.write("                            <th>Journey ID</th>\r\n");
      out.write("                            <th>Journey Name</th>\r\n");
      out.write("                            <th>Start Time</th>\r\n");
      out.write("                            <th>Arrival Time</th>\r\n");
      out.write("                            <th>Capacity</th>\r\n");
      out.write("                            <th>3rd Class Seat Count</th>\r\n");
      out.write("                            <th>Booked 3rd Class</th>\r\n");
      out.write("                            <th>1st Class Seat Count</th>\r\n");
      out.write("                            <th>Booked 1st Class</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>101</td>\r\n");
      out.write("                            <td>Express Line</td>\r\n");
      out.write("                            <td>1009WP</td>\r\n");
      out.write("                            <td>Colombo to Kandy</td>\r\n");
      out.write("                            <td>06:00 AM</td>\r\n");
      out.write("                            <td>09:30 AM</td>\r\n");
      out.write("                            <td>500</td>\r\n");
      out.write("                            <td>200</td>\r\n");
      out.write("                            <td>100</td>\r\n");
      out.write("                            <td>50</td>\r\n");
      out.write("                            <td>50</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>102</td>\r\n");
      out.write("                            <td>Coast Runner</td>\r\n");
      out.write("                            <td>1QE</td>\r\n");
      out.write("                            <td>Galle to Colombo</td>\r\n");
      out.write("                            <td>07:30 AM</td>\r\n");
      out.write("                            <td>10:00 AM</td>\r\n");
      out.write("                            <td>400</td>\r\n");
      out.write("                            <td>150</td>\r\n");
      out.write("                            <td>70</td>\r\n");
      out.write("                            <td>20</td>\r\n");
      out.write("                            <td>30</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>103</td>\r\n");
      out.write("                            <td>Mountain King</td>\r\n");
      out.write("                            <td>1001S</td>\r\n");
      out.write("                            <td>Nuwara Eliya to Colombo</td>\r\n");
      out.write("                            <td>05:30 AM</td>\r\n");
      out.write("                            <td>11:00 AM</td>\r\n");
      out.write("                            <td>450</td>\r\n");
      out.write("                            <td>100</td>\r\n");
      out.write("                            <td>120</td>\r\n");
      out.write("                            <td>30</td>\r\n");
      out.write("                            <td>40</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>104</td>\r\n");
      out.write("                            <td>Night Owl</td>\r\n");
      out.write("                            <td>11B</td>\r\n");
      out.write("                            <td>Colombo to Jaffna</td>\r\n");
      out.write("                            <td>10:00 PM</td>\r\n");
      out.write("                            <td>06:00 AM</td>\r\n");
      out.write("                            <td>600</td>\r\n");
      out.write("                            <td>250</td>\r\n");
      out.write("                            <td>120</td>\r\n");
      out.write("                            <td>60</td>\r\n");
      out.write("                            <td>70</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>105</td>\r\n");
      out.write("                            <td>Hill Climber</td>\r\n");
      out.write("                            <td>132A</td>\r\n");
      out.write("                            <td>Kandy to Ella</td>\r\n");
      out.write("                            <td>08:00 AM</td>\r\n");
      out.write("                            <td>12:00 PM</td>\r\n");
      out.write("                            <td>350</td>\r\n");
      out.write("                            <td>130</td>\r\n");
      out.write("                            <td>80</td>\r\n");
      out.write("                            <td>40</td>\r\n");
      out.write("                            <td>40</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("        <hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("         <div class=\"services\" id=\"services\"><!--our services-->\r\n");
      out.write("            <h1>Our Services</h1><br>\r\n");
      out.write("            <p>We are dedicated to offering services that simplify your travel experience from start to finish. Our online booking system is easy to use, allowing you to reserve your tickets in just a few clicks. In addition to booking, we offer real-time updates on train schedules and delays so you can plan your trip with confidence. Once onboard, stay connected with free Wi-Fi available in all coaches, and keep your devices powered up with convenient charging points at every seat. We also provide a selection of snacks and meals for you to enjoy during your trip. If you ever have a question or concern, our 24/7 customer service team is always available to assist. We aim to make every aspect of your journey as smooth and hassle-free as possible, whether you’re a daily commuter or traveling long-distance. Your comfort, convenience, and satisfaction are our top priorities as we strive to enhance your travel experience.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"History\" id=\"History\"><!--Our History-->\r\n");
      out.write("            <h1>Our History</h1><br>\r\n");
      out.write("            <p>Our journey began over two decades ago with the simple goal of connecting communities through reliable train services. What started as a small operation has grown into one of the country’s most trusted rail networks. Over the years, we have expanded our routes, introduced new services, and continually improved to meet the evolving needs of our passengers. From our humble beginnings to our present-day network, we have always focused on providing safe, comfortable, and efficient travel for our customers. Our history is marked by innovation, such as the introduction of digital ticketing, real-time updates, and premium onboard services. We take great pride in the relationships we’ve built with the cities and communities we serve. Our commitment to excellence has helped us earn the loyalty of millions of passengers over the years. As we continue to grow, we remain dedicated to offering the best possible travel experience for all of our passengers.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"Route\" id=\"Route\"><!--Our Route-->\r\n");
      out.write("            <h1>Our Route</h1><br>\r\n");
      out.write("            <p>Our extensive rail network connects cities and communities across the country, offering a convenient and efficient way to travel. Whether you’re commuting to work, visiting family, or embarking on a scenic journey, our routes are designed to get you where you need to go with ease. We operate on well-planned routes that minimize travel time while maximizing convenience, ensuring that you reach your destination quickly and comfortably. Our network spans both urban and rural areas, so whether you’re in a major city or a remote town, we have a route for you. Many of our routes feature breathtaking views of the countryside, coastlines, and mountains, making your journey not just about the destination but also the experience along the way. With frequent departures and arrivals, we offer flexibility to accommodate your schedule. Our goal is to provide you with a stress-free travel option that connects you to the places and people that matter most.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"Safety\" id=\"Safety\"><!--Our Commitment to Safety-->\r\n");
      out.write("            <h1>Our Commitment to Safety</h1><br>\r\n");
      out.write("            <p>Your safety is our highest priority, and we go above and beyond to ensure that every journey you take with us is secure. We have implemented state-of-the-art safety technologies on all of our trains, including advanced braking systems, surveillance cameras, and automated alerts to prevent potential hazards. Our trains undergo rigorous, regular inspections to ensure they meet the highest safety standards. In addition, all our staff are trained in emergency protocols and are equipped to handle any situation that may arise, giving you peace of mind throughout your journey. We also understand the importance of maintaining a clean environment onboard. Our cleaning crews thoroughly sanitize trains between journeys, and additional hygiene measures are in place to ensure a healthy travel experience. Whether it's safety from operational risks or health concerns, we take every precaution to protect our passengers, so you can enjoy a safe and worry-free trip every time.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <hr id=\"hr_line\">\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("\r\n");
      out.write("        document.getElementById('new_but2').addEventListener('click', function() {\r\n");
      out.write("            document.getElementById('services').scrollIntoView({ behavior: 'smooth' });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.getElementById('new_but5').addEventListener('click', function() {\r\n");
      out.write("            document.getElementById('Route').scrollIntoView({ behavior: 'smooth' }); // corrected to 'Route'\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.getElementById('new_but7').addEventListener('click', function() {\r\n");
      out.write("            document.getElementById('History').scrollIntoView({ behavior: 'smooth' }); // corrected to 'History'\r\n");
      out.write("        });\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"footer-container\">\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Quick Access</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("                <li><a href=\"#\">Our Services</a></li>\r\n");
      out.write("                <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                <li><a href=\"#\">Cancellation Program</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Get Help</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("                <li><a href=\"#\">History</a></li>\r\n");
      out.write("                <li><a href=\"#\">Route</a></li>\r\n");
      out.write("                <li><a href=\"#\">Special</a></li>\r\n");
      out.write("                <li><a href=\"#\">Reservation</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Train Reservation</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">VIP Reservation</a></li>\r\n");
      out.write("                <li><a href=\"#\">Early Booking</a></li>\r\n");
      out.write("                <li><a href=\"#\">Special Day</a></li>\r\n");
      out.write("                <li><a href=\"#\">Food Order</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Follow Us</h3>\r\n");
      out.write("            <div class=\"footer-social\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-linkedin\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("        \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
