/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2024-10-15 20:23:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class insertreview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String username = (String) session.getAttribute("username");
    if (username == null) {
        response.sendRedirect("Homepage.jsp");
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Add Review</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"CSS/insertreview.css\">\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        // JavaScript function to assign session 'username' to the 'userid' field\r\n");
      out.write("        function assignSessionToUserId() {\r\n");
      out.write("            document.getElementById(\"userid\").value = \"");
      out.print( username );
      out.write("\";\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!-- Ensure body calls the function on load -->\r\n");
      out.write("<body onload=\"assignSessionToUserId()\">\r\n");
      out.write("    <header class=\"navbar navbar-dark bg-secondary\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"AfterHomepage.jsp\" class=\"navbar-brand mx-2\">Home</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"addreview.jsp\" class=\"navbar-brand mx-2\">Review</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"navbar-nav\">\r\n");
      out.write("            \r\n");
      out.write("        </ul>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container mt-5\">\r\n");
      out.write("        <h2 class=\"mb-4 text-center\">Add a Review</h2>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Set form method to POST or GET -->\r\n");
      out.write("        <form action=\"insertReview\" class=\"p-4 shadow-sm rounded bg-light\" method=\"get\">\r\n");
      out.write("            <!-- User ID field will be automatically populated -->\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"userid\" class=\"form-label\">User name</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"userid\" name=\"userid\" readonly>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"trainnumber\" class=\"form-label\">Train Number</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"trainnumber\" name=\"trainnumber\" placeholder=\"Enter the Train Number\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"rating\" class=\"form-label\">Rating</label>\r\n");
      out.write("                <select class=\"form-select\" id=\"rating\" name=\"rating\" required>\r\n");
      out.write("                    <option value=\"\" disabled selected>Select a rating</option>\r\n");
      out.write("                    <option value=\"1\">1 - ⭐</option>\r\n");
      out.write("                    <option value=\"2\">2 - ⭐⭐</option>\r\n");
      out.write("                    <option value=\"3\">3 - ⭐⭐⭐</option>\r\n");
      out.write("                    <option value=\"4\">4 - ⭐⭐⭐⭐</option>\r\n");
      out.write("                    <option value=\"5\">5 - ⭐⭐⭐⭐⭐</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"review\" class=\"form-label\">Review</label>\r\n");
      out.write("                <textarea class=\"form-control\" id=\"review\" name=\"review\" rows=\"4\" placeholder=\"Write your review here...\" required></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"text-center\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-success\">Submit Review</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <footer>\r\n");
      out.write("    <div class=\"footer-container\">\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Quick Access</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("                <li><a href=\"#\">Our Services</a></li>\r\n");
      out.write("                <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                <li><a href=\"#\">Cancellation Program</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Get Help</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("                <li><a href=\"#\">History</a></li>\r\n");
      out.write("                <li><a href=\"#\">Route</a></li>\r\n");
      out.write("                <li><a href=\"#\">Special</a></li>\r\n");
      out.write("                <li><a href=\"#\">Reservation</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Train Reservation</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">VIP Reservation</a></li>\r\n");
      out.write("                <li><a href=\"#\">Early Booking</a></li>\r\n");
      out.write("                <li><a href=\"#\">Special Day</a></li>\r\n");
      out.write("                <li><a href=\"#\">Food Order</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Follow Us</h3>\r\n");
      out.write("            <div class=\"footer-social\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-linkedin\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
