/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2024-10-15 19:22:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Passenger Login Page</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/login.css\"> \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Header Section -->\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <h2>TrainGO</h2>\r\n");
      out.write("    <div class=\"mysts\">\r\n");
      out.write("        <a href=\"Homepage.jsp\"><button class=\"header_but\">Home</button></a>\r\n");
      out.write("        <a href=\"PassengerRegister.jsp\"><button class=\"header_but\">SignUp</button></a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Main Login Form Section -->\r\n");
      out.write("<div class=\"container\"> \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <form action=\"login\">\r\n");
      out.write("        <h1>Login</h1>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"content\"> \r\n");
      out.write("            <!-- Username Field -->\r\n");
      out.write("            <div class=\"input-box\">\r\n");
      out.write("                <label for=\"username\">Username</label>\r\n");
      out.write("                <input type=\"text\" id=\"username\" name=\"Username\" placeholder=\"Enter your username..\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Password Field -->\r\n");
      out.write("            <div class=\"input-box\">\r\n");
      out.write("                <label for=\"password\">Password</label>\r\n");
      out.write("                <div class=\"password-container\">\r\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter your password..\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"button-container\">\r\n");
      out.write("            <button type=\"submit\">Login</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("        <div class=\"alert\">\r\n");
      out.write("            <p>Forgot your password? <a href=\"#\">Click here</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"footer-container\">\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Quick Access</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">Home</a></li>\r\n");
      out.write("                <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("                <li><a href=\"#\">Our Services</a></li>\r\n");
      out.write("                <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                <li><a href=\"#\">Cancellation Program</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Get Help</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("                <li><a href=\"#\">History</a></li>\r\n");
      out.write("                <li><a href=\"#\">Route</a></li>\r\n");
      out.write("                <li><a href=\"#\">Special</a></li>\r\n");
      out.write("                <li><a href=\"#\">Reservation</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Train Reservation</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">VIP Reservation</a></li>\r\n");
      out.write("                <li><a href=\"#\">Early Booking</a></li>\r\n");
      out.write("                <li><a href=\"#\">Special Day</a></li>\r\n");
      out.write("                <li><a href=\"#\">Food Order</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"footer-column\">\r\n");
      out.write("            <h3>Follow Us</h3>\r\n");
      out.write("            <div class=\"footer-social\">\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                <a href=\"#\"><i class=\"fab fa-linkedin\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
